# Generated by Django 4.1.5 on 2023-01-27 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_add_slug_to_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="zip_code",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
